<?php

class RideState {
    const SENT_REQUEST_TO_DRIVER = "SENT_REQUEST_TO_DRIVER";
    const USER_CANCELLED_THE_RIDE = "USER_CANCELLED_THE_RIDE";
    const REQUEST_ACCEPTED_BY_DRIVER = "ACCEPTED_BY_DRIVER";
    const DRIVER_ARRIVED_AT_PICK_UP = "DRIVER_ARRIVED_AT_PICK_UP";
    const USER_STARTED_RIDE = "USER_STARTED_RIDE";
    const USER_REACHED_AT_DESTINATION = "USER_REACHED_AT_DESTINATION";
}